USE 21_SEP;
CREATE TABLE  NOBEL(
	YEAR INT NOT NULL,
    SUBJECT VARCHAR(50),
    WINNER VARCHAR(50),
    COUNTRY VARCHAR(50),
    CATEGORY VARCHAR(50)
);

DROP TABLE NOBEL;

SELECT * FROM NOBEL;

INSERT INTO NOBEL(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY)
VALUES(1970,"PHYSICS","HANNES ALFVEN","SWEDEN","SCIENTIST"),
(1970,"PHYSICS","LOUIS NEEL","FRANCE","SCIENTIST"),
(1970,"CHEMISTRY","LUIS FEDERCIO LELIOR","FRANCE","SCIENTIST"),
(1970,"PHYSIOLOGY","ULF VON EULER","SWEDEN","SCIENTIST"),
(1970,"PHYSIOLOGY","BERNARD KATZ","GERMANY","SCIENTIST"),
(1970,"LITERATURE","ALEKSANDR SOLZHENITSYN","RUSSIA","LINGUIST"),
(1970,"ECONOMICS","PAUL SAMUELSON","USA","ECONOMIST"),
(1970,"PHYSIOLOGY","JULIUS AXELROD","USA","SCIENSTIST"),
(1971,"PHYSICS","DENNIS GABOR","HUNGARY","SCIENTIST"),
(1971,"CHEMISTRY","GERHARD HERZBERG","GERMANY","SCIENTIST"),
(1971,"PEACE","WILLY BRANDT","GERMANY","CHANCELLOR"),
(1971,"LITERATURE","PABLO NERUDA","CHILE","LINGUIST"),
(1971,"ECONOMICS","SIMON KUZNETS","RUSSIA","ECONOMIST"),
(1978,"PEACE","ANWAR AL-SADAT","EGYPT","PRESIDENT"),	
(1978,"PEACE","MENACHEM BEGINN","ISRAEL","PRIME MINISTER"),
(1987,"CHEMISTRY","DONALD J. CRAM","USA","SCIENTIST"),
(1987,"CHEMISTRY","JEAN MARIE-LEHN","FRANCE","SCIENTIST"),
(1987,"PHYSIOLOGY","SUSUMU TONEGAWA","JAPAN","SCIENTIST"),
(1994,"ECONOMICS","REINHARD SELTEN","GERMANY","ECONOMIST"),
(1994,"PEACE","YITZHAK RABIN","ISRAEL","PRIME MINISTER"),
(1987,"PHYSICS","JOHANNES GEORG BEDNORZ","GERMANY","ECONOMIST"),
(1987,"LITERATURE","JOSEPH BRODSKY","RUSSIA","LINGUIST"),
(1987,"ECONOMICS","ROBERT SOLOW","USA","ECONOMIST"),
(1994,"LITERATURE","KENZABURO OE","JAPAN","LINGUIST");

-- Write sql query to find the nobel prize winners of the year 1970. Return year,subject 
-- and winner

SELECT YEAR,SUBJECT,WINNER
FROM NOBEL
WHERE YEAR = 1970;

-- Write sql query to retrieve the details of the winners whose first name matches with 
-- the string ‘Louis’. Return year,subject,winner,country 

SELECT YEAR,SUBJECT,WINNER,COUNTRY
FROM NOBEL
WHERE WINNER LIKE 'LOUIS %';

-- Write sql query to find the nobel prize winners in chemistry between the years 1965 
-- and 1975. Begin and end values are includedReturn year, subject, winner and 
-- country 

SELECT YEAR,SUBJECT,WINNER,COUNTRY
FROM NOBEL
WHERE SUBJECT = 'Chemistry'
AND YEAR BETWEEN 1965 AND 1975;

-- Write sql query to find Nobel prize winners for the subject that does not begin with 
-- the letter ‘P’. Order the result by year, descending and winner in ascending 

SELECT WINNER,YEAR,SUBJECT
FROM NOBEL
WHERE SUBJECT NOT LIKE 'P%'
ORDER BY YEAR DESC, WINNER ASC;


-- Write sql query to find the details of 1970 Nobel prize winners. Order the result by 
-- subject, ascending except for ‘Chemistry’   and ‘Economics’ which will come at the 
-- end of the result set. Return year, subject, winner , country and category.


SELECT YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY
FROM NOBEL
WHERE YEAR = 1970
ORDER BY 
    CASE 
        WHEN SUBJECT IN ('Chemistry', 'Economics') THEN 1 
        ELSE 0 
    END, 
    SUBJECT ASC;