-- cursor used to display individual records.
USE 21_SEP;

SELECT * FROM EMP_DATA;

DELIMITER $$
CREATE PROCEDURE DISPLAY_CURSOR()
BEGIN
	declare VAR_ID INT;
    DECLARE VAR_NAME VARCHAR(50);
    DECLARE VAR_FINISH INT DEFAULT 0;
    DECLARE CUR CURSOR FOR SELECT ID,NAME FROM EMP_DATA;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VAR_FINISH=1;
    
OPEN CUR;
	GET_DATA:LOOP
		FETCH CUR INTO VAR_ID,VAR_NAME;
        SELECT CONCAT(VAR_ID,CONCAT(' - ',VAR_NAME));
        
        IF VAR_FINISH=1
			THEN LEAVE GET_DATA;
		END IF;
        
        
        END LOOP GET_DATA;
CLOSE CUR;
END $$


CALL DISPLAY_CURSOR();