USE 21_SEP;
CREATE TABLE EMPLOYEE_DATA(

	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(50),
    EMP_SALARY INT NOT NULL,
    EMP_AGE INT CHECK(EMP_AGE>18),
    EMP_BRANCH VARCHAR(50)
    );

CREATE TABLE DEPARTMENT_DATA(

	DEP_ID INT,
    DEP_NAME VARCHAR(50),
    EMP_ID INT,
    FOREIGN KEY DEPARTMENT_DATA(EMP_ID) REFERENCES EMPLOYEE_DATA(EMP_ID)
);

DROP TABLE DEPARTMENT_DATA;
INSERT INTO EMPLOYEE_DATA VALUES
(1001,"AADHYA",50000,20,"COMPUTER SCIENCE"),
(1002,"ABHISHEK",5000000,20,"COMPUTER SCIENCE"),
(1041,"RISHIKA",50000,20,"COMPUTER SCIENCE"),
(1003,"YASH",500000,20,"COMPUTER SCIENCE");
 


TRUNCATE TABLE EMPLOYEE_DATA;

SELECT * FROM EMPLOYEE_DATA;

SELECT * FROM DEPARTMENT_DATA;

INSERT INTO DEPARTMENT_DATA VALUES	
(101,"GATE",1001),
(102,"SOFTWARE ENGG.",1002),
(103,"FULL STACK",1041),
(104,"GOV.",1004),
(105,"MBA",1003);


select * from EMPLOYEE_DATA as e left join DEPARTMENT_DATA as d on e.EMP_ID=d.DEP_ID
union
select * from EMPLOYEE_DATA as e right join DEPARTMENT_DATA as d on e.EMP_ID=d.DEP_ID;

