USE 21_SEP;
CREATE TABLE SALESPERSON(
	SNO INT PRIMARY KEY,
    SNAME VARCHAR(50),
    CITY VARCHAR(50),
    COMM VARCHAR(50)
    );

INSERT INTO SALESPERSON (SNO,SNAME,CITY,COMM)
VALUES(1001,"PEEL","LONDON",".12"),
(1002,"SERRES","SAN JOSE",".13"),
(1004,"MOTIKA","LONDON",".11"),
(1007,"RAFKIN","BARCELONA",".15"),
(1003,"AXELROD","NEW YORK",".10");

SELECT * FROM SALESPERSON;
SELECT * FROM CUSTOMER;

CREATE TABLE CUSTOMER(
	CNM INT PRIMARY KEY AUTO_INCREMENT,
    CNAME VARCHAR(50),
    CITY VARCHAR(50),
    RATING INT(10),
    SNO INT,
    
    FOREIGN KEY CUSTOMER(SNO) REFERENCES SALESPERSON(SNO)
);
INSERT INTO CUSTOMER(CNM,CNAME,CITY,RATING,SNO)
VALUES(201,"HOFFMAN","LONDON",100,1001);

INSERT INTO CUSTOMER(CNAME,CITY,RATING,SNO)
VALUES("GIOVANNE","ROE",200,1003),
("LIU","SAN JOSE",300,1002),
("GRASS","BARCELONA",100,1002),
("CELMENS","LONDON",300,1007),
("PERERIA","ROE",100,1004);

-- 1. Retrieve the below data from above table 

SELECT * FROM SALESPERSON;
SELECT * FROM CUSTOMER;

-- 2.All orders for more than $1000. 
SELECT * FROM CUSTOMER
WHERE RATING>100;

-- 3. Names and cities of all salespeople in London with commission above 0.12 

SELECT SNAME,CITY FROM SALESPERSON
WHERE  CITY='LONDON' AND COMM>0.12;

-- 4.All salespeople either in Barcelona or in London.

SELECT * FROM SALESPERSON
WHERE CITY = 'BARCELONA' OR CITY= 'LONDON';

-- 5. All salespeople with commission between 0.10 and 0.12. (Boundary 
-- valuesshould be excluded). 

  SELECT * FROM SALESPERSON
  WHERE COMM>=0.10 AND COMM<=0.12;
  
  -- 6.All customers excluding those with rating <= 100 unless they are located 
-- inRome. 

SELECT * FROM CUSTOMER
WHERE RATING>100 OR CITY='ROME';